// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIWritingAssistantService_AskAI_FullMethodName = "/servicepb.AIWritingAssistantService/AskAI"
)

// AIWritingAssistantServiceClient is the client API for AIWritingAssistantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIWritingAssistantServiceClient interface {
	AskAI(ctx context.Context, in *AskAIRequest, opts ...grpc.CallOption) (*AskAIResponse, error)
}

type aIWritingAssistantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIWritingAssistantServiceClient(cc grpc.ClientConnInterface) AIWritingAssistantServiceClient {
	return &aIWritingAssistantServiceClient{cc}
}

func (c *aIWritingAssistantServiceClient) AskAI(ctx context.Context, in *AskAIRequest, opts ...grpc.CallOption) (*AskAIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskAIResponse)
	err := c.cc.Invoke(ctx, AIWritingAssistantService_AskAI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIWritingAssistantServiceServer is the server API for AIWritingAssistantService service.
// All implementations must embed UnimplementedAIWritingAssistantServiceServer
// for forward compatibility.
type AIWritingAssistantServiceServer interface {
	AskAI(context.Context, *AskAIRequest) (*AskAIResponse, error)
	mustEmbedUnimplementedAIWritingAssistantServiceServer()
}

// UnimplementedAIWritingAssistantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIWritingAssistantServiceServer struct{}

func (UnimplementedAIWritingAssistantServiceServer) AskAI(context.Context, *AskAIRequest) (*AskAIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskAI not implemented")
}
func (UnimplementedAIWritingAssistantServiceServer) mustEmbedUnimplementedAIWritingAssistantServiceServer() {
}
func (UnimplementedAIWritingAssistantServiceServer) testEmbeddedByValue() {}

// UnsafeAIWritingAssistantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIWritingAssistantServiceServer will
// result in compilation errors.
type UnsafeAIWritingAssistantServiceServer interface {
	mustEmbedUnimplementedAIWritingAssistantServiceServer()
}

func RegisterAIWritingAssistantServiceServer(s grpc.ServiceRegistrar, srv AIWritingAssistantServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIWritingAssistantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIWritingAssistantService_ServiceDesc, srv)
}

func _AIWritingAssistantService_AskAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWritingAssistantServiceServer).AskAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWritingAssistantService_AskAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWritingAssistantServiceServer).AskAI(ctx, req.(*AskAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIWritingAssistantService_ServiceDesc is the grpc.ServiceDesc for AIWritingAssistantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIWritingAssistantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.AIWritingAssistantService",
	HandlerType: (*AIWritingAssistantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskAI",
			Handler:    _AIWritingAssistantService_AskAI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
