// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AI int32

const (
	AI_CHATGPT AI = 0
	AI_CLAUDE  AI = 1
	AI_LLAMA   AI = 2
)

// Enum value maps for AI.
var (
	AI_name = map[int32]string{
		0: "CHATGPT",
		1: "CLAUDE",
		2: "LLAMA",
	}
	AI_value = map[string]int32{
		"CHATGPT": 0,
		"CLAUDE":  1,
		"LLAMA":   2,
	}
)

func (x AI) Enum() *AI {
	p := new(AI)
	*p = x
	return p
}

func (x AI) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AI) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (AI) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x AI) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AI.Descriptor instead.
func (AI) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type AskAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiSelected    []AI                   `protobuf:"varint,1,rep,packed,name=ai_selected,json=aiSelected,proto3,enum=servicepb.AI" json:"ai_selected,omitempty"`
	RequestText   string                 `protobuf:"bytes,2,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskAIRequest) Reset() {
	*x = AskAIRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskAIRequest) ProtoMessage() {}

func (x *AskAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskAIRequest.ProtoReflect.Descriptor instead.
func (*AskAIRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *AskAIRequest) GetAiSelected() []AI {
	if x != nil {
		return x.AiSelected
	}
	return nil
}

func (x *AskAIRequest) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

type AIModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         AI                     `protobuf:"varint,1,opt,name=model,proto3,enum=servicepb.AI" json:"model,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIModelResponse) Reset() {
	*x = AIModelResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIModelResponse) ProtoMessage() {}

func (x *AIModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIModelResponse.ProtoReflect.Descriptor instead.
func (*AIModelResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *AIModelResponse) GetModel() AI {
	if x != nil {
		return x.Model
	}
	return AI_CHATGPT
}

func (x *AIModelResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type AskAIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*AIModelResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskAIResponse) Reset() {
	*x = AskAIResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskAIResponse) ProtoMessage() {}

func (x *AskAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskAIResponse.ProtoReflect.Descriptor instead.
func (*AskAIResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *AskAIResponse) GetResponses() []*AIModelResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tservicepb\"a\n" +
	"\fAskAIRequest\x12.\n" +
	"\vai_selected\x18\x01 \x03(\x0e2\r.servicepb.AIR\n" +
	"aiSelected\x12!\n" +
	"\frequest_text\x18\x02 \x01(\tR\vrequestText\"R\n" +
	"\x0fAIModelResponse\x12#\n" +
	"\x05model\x18\x01 \x01(\x0e2\r.servicepb.AIR\x05model\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"I\n" +
	"\rAskAIResponse\x128\n" +
	"\tresponses\x18\x01 \x03(\v2\x1a.servicepb.AIModelResponseR\tresponses*(\n" +
	"\x02AI\x12\v\n" +
	"\aCHATGPT\x10\x00\x12\n" +
	"\n" +
	"\x06CLAUDE\x10\x01\x12\t\n" +
	"\x05LLAMA\x10\x022W\n" +
	"\x19AIWritingAssistantService\x12:\n" +
	"\x05AskAI\x12\x17.servicepb.AskAIRequest\x1a\x18.servicepb.AskAIResponseB>Z<github.com/ManoVikram/AI-Writing-Assistant/backend/api/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(AI)(0),                 // 0: servicepb.AI
	(*AskAIRequest)(nil),    // 1: servicepb.AskAIRequest
	(*AIModelResponse)(nil), // 2: servicepb.AIModelResponse
	(*AskAIResponse)(nil),   // 3: servicepb.AskAIResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: servicepb.AskAIRequest.ai_selected:type_name -> servicepb.AI
	0, // 1: servicepb.AIModelResponse.model:type_name -> servicepb.AI
	2, // 2: servicepb.AskAIResponse.responses:type_name -> servicepb.AIModelResponse
	1, // 3: servicepb.AIWritingAssistantService.AskAI:input_type -> servicepb.AskAIRequest
	3, // 4: servicepb.AIWritingAssistantService.AskAI:output_type -> servicepb.AskAIResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
